### ISSUE TITLE
Problem when installing src.rock 1.16.0-1 from luarocks

### ISSUE THREAD

**Issue by teto** [keplerproject/coxpcall#15]
There seems to be a problem with the src.rock for coxpcall-1.16.0-1
`Error: Failed initializing build back-end for build type 'bultin': module 'luarocks.build.bultin' not found:No LuaRocks module found for luarocks.build.bultin`
It should be 'builtin' instead of 'bultin'.

**Comment by hishamhm** [comment]
I just uploaded 1.17, which does not have the problem! Thanks!

**Comment by teto** [comment]
thanks !
