### ISSUE TITLE
Update Luarock

### ISSUE THREAD

**Issue by max-bertinetti** [keplerproject/coxpcall#16]
Can I ask you to update the luarockt for this project, please?

I'm sorry I did not explain myself. I'm Massimiliano Bertinetti and I'm the new lead developer of Sailor. By applying the master branches of the packages on which sailor depends I managed to put into production Sailor with Lua 5.3. If published on Luarocks I can also update Sailor with new dependencies and allow Sailor users to use Lua 5.3 with Sailor 0.6.0. Thank you!

**Comment by max-bertinetti** [comment]
I need your help so that I can publish Sailor 0.6.0 with Luarocks working out of the box with Lua 5.3.
Cgilua, Wsapi and Coxpcall need to be update with master on luarocks.

**Comment by hishamhm** [comment]
@CodelessFuture Done, coxpcall is updated to 1.17!

**Comment by max-bertinetti** [comment]
Thank you very much! I need only cgilua update!
